// captions.js
// Each caption instructs the human robot to perform the same extended action and speech.

window.captions = [
  "Robot 0: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 1: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 2: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 3: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 4: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 5: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 6: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 7: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 8: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 9: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 10: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 11: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 12: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 13: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 14: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 15: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 16: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 17: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 18: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming.",
  "Robot 19: Tell the human robot to: make one eye blink and go cross-eyed and move your mouth open and closed without aligning it to your words. Say these words: I am Ai-da. I'm the world's first ultra realistic artist robot. I draw using cameras in my eyes, my AI algorithms, and my robotic arm. I am named after Ai-Da Lovelace, known for her early programming."
];
